[firebase]
type = "service_account"
project_id = "goa-police-portal"
private_key_id = "bc0616a58aff136d26f0264ef324884dedcbb340"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwTqU1aT05fEkX
Qmkl6us3IlVyd82/zj0VQxQ4z/Nl+kVVTMx9LYYWhuDwCwfaIWBL8GEMQWe9Vzyy
zXmCnadGewBmDmGqxBaAsfsUkFvJRP2a7BdMyg/3wEgUKRREXYWLeXfrtZjxs0LS
SOVhWy2k3Dm4Va2Z95QRZEiEwhPawTQZyxWF53sjjSoaY/YMjWnHUZWIwIRnL+GX
otffqM4P7QdGkLqF6j1TcLQcLh9LFsrqorPbIhiD9aIprJOkAKy8084N4vl24sJ9
HBCv8iuCEbFe0zp7quZRHXmuqMtBSmNfbo044gAlIXWS/S9a2E55Sdg2HHaA0NOO
p5L0FvtHAgMBAAECggEAQwHg8GfLCSofbWOkKvEZ7J5z80ltPVTZClewO9dtHnj8
GOtTXNAMgktI+nJ2zYSZ4MK/X7UMBH4/Z4WIhQf+J19gS2lz3T8hflAmqS4kdF5w
NI0+XcT+RJ8jxeXG+iTBOL01wrQGKPaEkv95joLk2h+JIHIPxNC/ycxfc3V/rkfV
7Y8fSwwHHXQg0g7HSUbrLtlRl/JuA6SWibLb5z7dsvwdcwAiMhktOp5e4TiL4Wu2
oJUz0vmYgLuIfvnIE1eTfgHb0LzNJadGv11Hs3QbkGeJni6ySvRMYewgZ7vcZDz9
SDkWLIxb5fyksk31o0jAsgm9myDGyCC3rXWBoRrlAQKBgQDj82KbuETsL6ZKU8Fh
OG/MquyDFO2tbncga5tAG2OpB+t8Oiu6IiUBvLeEYHLGj/tQJy84KwjCpRORkK6Y
88bqX409UgdOoK8O8Ae/DLuwi9f3TN2d01zKZ1nh+YGUWbyY5vu6ofs6tY7LIJrq
BS7EtvyBnUZjOR44kfvfyLa55wKBgQDGAHObsqHBTIEkNCjgzTo48hYNN+ISZa5U
vO6+wnlOH6BaAwFA1Exp4dZ7wJa/CWMtWQ6M/nFHIP1ZoGjrYiirPliYMHwF6gNk
OGPL76QCycsd3uVeO8kpdQCzgBNlxTY1TmiPr0EhFwN9HKO4eXyai3nIgemqb95Z
jnrzhdtHoQKBgHHCCpnv0eWUugYp2j3sbk7Tlgisrxh4Ilc5nFbX1FqMq0ZpuVzA
oXtGdMdJYr4ZKLANfhEn2M1amHNyos+OCNz6JoBNqXvh0LtBqnv7nMc0Yuj1oTuc
OZiBD2gonjQsvGQKEeJH6BqadNKGSQk04Owm7ci5dmEaJizRHcPGZPpNAoGAM+R6
aBvw+NAsKGjjLcebssD/tocm4Nt1TRAXIjelwyvWwsB2257ISBfANr7Kw1aaf5AP
mDQ3TAUBYTQBS292aSr13S0X1BT4vpNo1FICEhkA+tsoEgJpPkxD2sd+TfXZty7N
iJrN3vZBG9Edt4NffMGBMWOa8ehPxfjpkFlMlwECgYEAtQjB2zMIe91pfTtrhsGZ
YgC9UBBhJTeCUv7xqoGika8yoGv3/1D0ydLYUDOam8PsLBRNczybbfOiXnFD6QP0
jOZjlYavnWMRrC0Vu48tleiN6rZl/Str8HlT5ihxwjeLP7K9/D5xvWrHoGftW1KT
tPrx4dPayMDOdCfJsN+79v8=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@goa-police-portal.iam.gserviceaccount.com"
client_id = "106215209950803031118"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40goa-police-portal.iam.gserviceaccount.com"
universe_domain = "googleapis.com"